name: deploy jar to github packages
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERSION_ID: ${{secrets.SNAPSHOT_VERSION_ID}}
    permissions:
      contents: read
      packages: write
    steps:
      - name: delete old snapthos
        run: |   
          curl -L \
                -X DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/user/packages/maven/me.yceel.mockito.mockito-static-mockmaker/versions/$VERSION_ID
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Publish package
        run: mvn --batch-mode deploy
