name: deploy jar to github packages
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: delete whole package (old snapthos)
        if: ${{ vars.DELETE == 'true' }}
        run: |   
          curl -L \
                -X DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/users/reminia/packages/maven/me.yceel.mockito.mockito-static-mockmaker
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Publish package
        run: mvn --batch-mode deploy
